# Generated by Django 3.0 on 2021-01-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('date_created', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
