# Generated by Django 3.0 on 2021-01-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerModel',
            new_name='Customer',
        ),
    ]
